### ISSUE TITLE
Clicking "Blocks" on Farmer Details page disables all of the 4 tabs

### ISSUE THREAD

**Issue by atomsymbol** [openchia/web#143]
This issue is reproducible in the case of a farmer who hasn't won any block, for example: https://openchia.io/en/explorer/farmer/bf98d9561809b923fa84acefefa9604ab5160f6821c5e8f3a58c7b79b27793e9

The tabs "Partials", "Payouts", "Blocks" and "Giveaways" stop working after the "Block" tab is clicked.

**Comment by atomsymbol** [comment]
````
ERROR TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at e.blocksEffortAverage (main.f576268a39e289a6e774.js:3:1134478)
    at oZ (main.f576268a39e289a6e774.js:3:1122283)
    at Jr (main.f576268a39e289a6e774.js:3:508408)
    at Xr (main.f576268a39e289a6e774.js:3:507036)
    at main.f576268a39e289a6e774.js:3:507431
    at Xr (main.f576268a39e289a6e774.js:3:507456)
    at main.f576268a39e289a6e774.js:3:507431
    at Xr (main.f576268a39e289a6e774.js:3:507456)
    at main.f576268a39e289a6e774.js:3:507431
````

**Comment by djerfy** [comment]
Fix done, thanks
