### ISSUE TITLE
Fieldset for notifications

### ISSUE THREAD

**Issue by atomsymbol** [openchia/web#236]
`https://openchia.io/en/explorer/login?launcher_id=...`

![Screenshot_20220305_195500](https://user-images.githubusercontent.com/22368256/156896531-5771755b-1498-44d4-8fdf-f349fa720c84.png)

The following errors are displayed in Google Chrome console:

````
main.2ce9462fdc938412.js:3 ERROR TypeError: Cannot read properties of null (reading 'includes')
    at XU (main.2ce9462fdc938412.js:3:650000)
    at fg (main.2ce9462fdc938412.js:3:962064)
    at jo (main.2ce9462fdc938412.js:3:960732)
    at TD (main.2ce9462fdc938412.js:3:961133)
    at jo (main.2ce9462fdc938412.js:3:961158)
    at TD (main.2ce9462fdc938412.js:3:961133)
    at jo (main.2ce9462fdc938412.js:3:961158)
    at TD (main.2ce9462fdc938412.js:3:961133)
    at jo (main.2ce9462fdc938412.js:3:961158)
    at AD (main.2ce9462fdc938412.js:3:967579)
main.2ce9462fdc938412.js:3 ERROR TypeError: Cannot read properties of null (reading 'includes')
    at XU (main.2ce9462fdc938412.js:3:650000)
    at fg (main.2ce9462fdc938412.js:3:962064)
    at jo (main.2ce9462fdc938412.js:3:960732)
    at TD (main.2ce9462fdc938412.js:3:961133)
    at jo (main.2ce9462fdc938412.js:3:961158)
    at TD (main.2ce9462fdc938412.js:3:961133)
    at jo (main.2ce9462fdc938412.js:3:961158)
    at TD (main.2ce9462fdc938412.js:3:961133)
    at jo (main.2ce9462fdc938412.js:3:961158)
    at AD (main.2ce9462fdc938412.js:3:967579)
````

**Comment by william-gr** [comment]
Thanks, page should be working now.

**Comment by atomsymbol** [comment]
It works OK now.

----

When I looked at this page (screenshot below) for the first time, it wasn't obvious to me where the checkbox "Mobile Push Notifications" belongs conceptually. I suggest updating the visual appearance of this page so that it is more obvious that the 1st checkbox belongs to "Notify on Payment" and that the 2nd checkbox belongs to "Notify on Farm Size Drop".

![Screenshot_20220305_202817](https://user-images.githubusercontent.com/22368256/156897433-9f5436f9-0247-481a-b328-3cc7bc1f4ee3.png)

**Comment by william-gr** [comment]
Good idea

**Comment by djerfy** [comment]
Hi @atomsymbol, it's better?

![image](https://user-images.githubusercontent.com/2886596/158235113-7292869b-7e57-4320-a88c-d9e828f93711.png)

**Comment by atomsymbol** [comment]
Yes, it looks more intuitive now in my opinion. Thanks.
